# env should be created with mamba
name: img_caption
channels:
  - conda-forge
dependencies:
  - python=3.9.5
  - pip
  # SCICOMP
  - numpy=1.21.4
  - scipy=1.7.2
  - pandas=1.3.4
  - matplotlib>=2.1.1
  - tqdm>=4.19.4
  - scikit-learn>=0.19.1
  - scikit-image>=0.13.1
  - seaborn>=0.8.1
  - ipykernel
  - pyarrow 
  - jupyter
  - timm
  - pip:
    - ipypb
    - opencv-python>=3.2.0.6
    - nltk>=3.2.2